apiVersion: v1
kind: Service
metadata:
  name: argocd-ui
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: argocd-ui
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
