apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: traefik
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: traefik
  sessionAffinity: None
