apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: oci-bv-20vpus-xfs
provisioner: blockvolume.csi.oraclecloud.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  vpusPerGB: "20"
  csi.storage.k8s.io/fstype: xfs
